# -*- coding: utf-8 -*-
Option.create(:key => "facebook_app_id", :string_value => "615270258487238")
Option.create(:key => "facebook_secret_id", :string_value => "a0393230a7ff017fbc8d230b3fe9d567")

City.find_or_create_by_key(:key => "aguja_sur_cerro", :name => "Aguja Sur Cerro")
City.find_or_create_by_key(:key => "alto_rio_mayo", :name => "Alto Río Mayo")
City.find_or_create_by_key(:key => "alvarez_canadon", :name => "Alvarez Cañadón")
City.find_or_create_by_key(:key => "apeleg_arroyo", :name => "Apeleg Arroyo")
City.find_or_create_by_key(:key => "astra", :name => "Astra")
City.find_or_create_by_key(:key => "azul_cerro", :name => "Azul Cerro")
City.find_or_create_by_key(:key => "blancas_islas", :name => "Blancas Islas")
City.find_or_create_by_key(:key => "camarones_bahia", :name => "Camarones Bahía")
City.find_or_create_by_key(:key => "chico_rio", :name => "Chico Río")
City.find_or_create_by_key(:key => "chubut_rio", :name => "Chubut Río")
City.find_or_create_by_key(:key => "corcovado", :name => "Corcovado")
City.find_or_create_by_key(:key => "de_esquel_cordon", :name => "De Esquel Cordón")
City.find_or_create_by_key(:key => "dolavon", :name => "Dolavon")
City.find_or_create_by_key(:key => "el_maiten", :name => "El Maitén")
City.find_or_create_by_key(:key => "epuyen_lago", :name => "Epuyén Lago")
City.find_or_create_by_key(:key => "facundo", :name => "Facundo")
City.find_or_create_by_key(:key => "gaiman", :name => "Gaiman")
City.find_or_create_by_key(:key => "general_mosconi", :name => "General Mosconi")
City.find_or_create_by_key(:key => "gualjaina", :name => "Gualjaina")
City.find_or_create_by_key(:key => "lago_amutui_quimei", :name => "Lago Amutui Quimei")
City.find_or_create_by_key(:key => "parque_nacional_lago_puelo", :name => "Parque Nacional Lago Puelo")
City.find_or_create_by_key(:key => "peninsula_valdes", :name => "Peninsula Valdes")
City.find_or_create_by_key(:key => "puerto_madryn", :name => "Puerto Madryn")
City.find_or_create_by_key(:key => "rada_tilly", :name => "Rada Tilly")
City.find_or_create_by_key(:key => "rio_mayo", :name => "Río Mayo")
City.find_or_create_by_key(:key => "sarmiento", :name => "Sarmiento")
City.find_or_create_by_key(:key => "sierra_chata", :name => "Sierra Chata")
City.find_or_create_by_key(:key => "steffen_cerro", :name => "Steffen Cerro")
City.find_or_create_by_key(:key => "taquetren_sierra", :name => "Taquetrén Sierra")
City.find_or_create_by_key(:key => "tova_isla", :name => "Tova Isla")
City.find_or_create_by_key(:key => "tres_picos_cerro", :name => "Tres Picos Cerro")
City.find_or_create_by_key(:key => "triste_monte", :name => "Triste Monte")
City.find_or_create_by_key(:key => "alto_de_las_plumas", :name => "Alto De Las Plumas")
City.find_or_create_by_key(:key => "alto_rio_senguer", :name => "Alto Río Senguer")
City.find_or_create_by_key(:key => "ameghino_punta", :name => "Ameghino Punta")
City.find_or_create_by_key(:key => "archibarca_cerro", :name => "Archibarca, Cerro")
City.find_or_create_by_key(:key => "atlas_punta", :name => "Atlas Punta")
City.find_or_create_by_key(:key => "bahia_bustamante", :name => "Bahía Bustamante")
City.find_or_create_by_key(:key => "camarones", :name => "Camarones")
City.find_or_create_by_key(:key => "aguja_sur_cerro", :name => "Aguja Sur Cerro")
City.find_or_create_by_key(:key => "canquel", :name => "Canquel")
City.find_or_create_by_key(:key => "cholila", :name => "Cholila")
City.find_or_create_by_key(:key => "comodoro_rivadavia", :name => "Comodoro Rivadavia")
City.find_or_create_by_key(:key => "cushamen", :name => "Cushamen")
City.find_or_create_by_key(:key => "de_la_virgen_cerro", :name => "De La Virgen Cerro")
City.find_or_create_by_key(:key => "el_hoyo", :name => "El Hoyo")
City.find_or_create_by_key(:key => "epuyen", :name => "Epuyén")
City.find_or_create_by_key(:key => "esquel", :name => "Esquel")
City.find_or_create_by_key(:key => "florentino_ameghino", :name => "Florentino Ameghino")
City.find_or_create_by_key(:key => "garayalde", :name => "Garayalde")
City.find_or_create_by_key(:key => "gobernador_costa", :name => "Gobernador Costa")
City.find_or_create_by_key(:key => "jose_de_san_martin", :name => "José De San Martín")
City.find_or_create_by_key(:key => "lago_puelo", :name => "Lago Puelo")
City.find_or_create_by_key(:key => "paso_de_indios", :name => "Paso De Indios")
City.find_or_create_by_key(:key => "playa_union", :name => "Playa Unión")
City.find_or_create_by_key(:key => "puerto_piramides", :name => "Puerto Piramides")
City.find_or_create_by_key(:key => "rawson", :name => "Rawson")
City.find_or_create_by_key(:key => "rio_pico", :name => "Río Pico")
City.find_or_create_by_key(:key => "seca_laguna", :name => "Seca Laguna")
City.find_or_create_by_key(:key => "solano_bahia", :name => "Solano Bahía")
City.find_or_create_by_key(:key => "talagapa", :name => "Talagapa")
City.find_or_create_by_key(:key => "telsen", :name => "Telsen")
City.find_or_create_by_key(:key => "trelew", :name => "Trelew")
City.find_or_create_by_key(:key => "trevelin", :name => "Trevelín")
City.find_or_create_by_key(:key => "verde_laguna", :name => "Verde Laguna")
puts "Cities created"

compra_venta = Category.find_or_create_by_key(:key => "compra_venta", :name => "Compra - Venta")
compra_venta.sub_categories.find_or_create_by_key(:key => "animales_y_mascotas", :name => "Animales y Mascotas")
compra_venta.sub_categories.find_or_create_by_key(:key => "cd_dvd", :name => "CD - DVD")
compra_venta.sub_categories.find_or_create_by_key(:key => "comida", :name => "Comida y Alimentos")
compra_venta.sub_categories.find_or_create_by_key(:key => "celulares_y_telefonos", :name => "Celulares y Teléfonos")
compra_venta.sub_categories.find_or_create_by_key(:key => "coleccionables", :name => "Coleccionables")
compra_venta.sub_categories.find_or_create_by_key(:key => "computacion_y_electronica", :name => "Computación y Electrónica")
compra_venta.sub_categories.find_or_create_by_key(:key => "instrumentos_musicales", :name => "Instrumentos Musicales")
compra_venta.sub_categories.find_or_create_by_key(:key => "electrodomesticos", :name => "Electrodomésticos")
compra_venta.sub_categories.find_or_create_by_key(:key => "deportes", :name => "Deportes")
compra_venta.sub_categories.find_or_create_by_key(:key => "fotografia_y_video", :name => "Fotografía y Video")
compra_venta.sub_categories.find_or_create_by_key(:key => "libros_y_revistas", :name => "Libros y Revistras")
compra_venta.sub_categories.find_or_create_by_key(:key => "hogar", :name => "Hogar")
compra_venta.sub_categories.find_or_create_by_key(:key => "bebes y niños", :name => "Bebés y Niños")
compra_venta.sub_categories.find_or_create_by_key(:key => "joyas_y_relojes", :name => "Joyas y Relojes")
compra_venta.sub_categories.find_or_create_by_key(:key => "indumentaria", :name => "Indumentaria")
compra_venta.sub_categories.find_or_create_by_key(:key => "juguetes_y_juegos", :name => "Juguetes y Juegos")
compra_venta.sub_categories.find_or_create_by_key(:key => "salud_y_belleza", :name => "Salud y Belleza")
compra_venta.sub_categories.find_or_create_by_key(:key => "videojuegos", :name => "Videojuegos")
compra_venta.sub_categories.find_or_create_by_key(:key => "otras_categorias", :name => "Otras Categorías")

inmuebles = Category.find_or_create_by_key(:key => "inmuebles", :name => "Inmuebles")
inmuebles.sub_categories.find_or_create_by_key(:key => "terrenos_y_lotes", :name => "Terrenos y Lotes")
inmuebles.sub_categories.find_or_create_by_key(:key => "locales_y_oficinas", :name => "Locales y Oficinas")
inmuebles.sub_categories.find_or_create_by_key(:key => "estacionamiento", :name => "Estacionamiento")
inmuebles.sub_categories.find_or_create_by_key(:key => "en_venta", :name => "En Venta")
inmuebles.sub_categories.find_or_create_by_key(:key => "en_alquiler", :name => "En Alquiler")


vehiculos_y_accesorios = Category.find_or_create_by_key(:key => "vehiculos_y_accesorios", :name => "Vehículos y Accesorios")
vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "autos", :name => "Autos")
vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "camiones", :name => "Camiones")
vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "camionetas", :name => "Camionetas")
vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "colectivos", :name => "Colectivos")
vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "motos_y_cuatriciclos", :name => "Motos y Cuatriciclos")
vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "barcos_y_veleros", :name => "Barcos y Veleros")
vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "aviones_y_avionetas", :name => "Aviones y Avionetas")
vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "otras_categorias", :name => "Otras Categorías")


empleo = Category.find_or_create_by_key(:key => "empleo", :name => "Empleo")
empleo.sub_categories.find_or_create_by_key(:key => "abogado", :name => "Abogado")
empleo.sub_categories.find_or_create_by_key(:key => "administrativo", :name => "Administrativo")
empleo.sub_categories.find_or_create_by_key(:key => "animador_y_actor", :name => "Animador y Actor")
empleo.sub_categories.find_or_create_by_key(:key => "comercial", :name => "Comercial")
empleo.sub_categories.find_or_create_by_key(:key => "construccion_y_obras", :name => "Construcción y Obras")
empleo.sub_categories.find_or_create_by_key(:key => "contador_y_financiero", :name => "Contador y Financiero")
empleo.sub_categories.find_or_create_by_key(:key => "educacion", :name => "Educación")
empleo.sub_categories.find_or_create_by_key(:key => "hoteleria_y_turismo", :name => "Hotelería y Turismo")
empleo.sub_categories.find_or_create_by_key(:key => "informatica_y_multimedia", :name => "Informática y Multimedia")
empleo.sub_categories.find_or_create_by_key(:key => "ingeniero", :name => "Ingeniero")
empleo.sub_categories.find_or_create_by_key(:key => "inmobiliaria", :name => "Inmobiliaria")
empleo.sub_categories.find_or_create_by_key(:key => "publicidad_y_marketing", :name => "Publicidad y Marketing")
empleo.sub_categories.find_or_create_by_key(:key => "medicina_y_salud", :name => "Medicina y Salud")
empleo.sub_categories.find_or_create_by_key(:key => "operario", :name => "Operario")
empleo.sub_categories.find_or_create_by_key(:key => "relaciones_publicas", :name => "Relaciones Públicas")
empleo.sub_categories.find_or_create_by_key(:key => "recursos_humanos", :name => "Recursos Humanos")
empleo.sub_categories.find_or_create_by_key(:key => "mozos_y_restaurantes", :name => "Mozos y Restaurantes")
empleo.sub_categories.find_or_create_by_key(:key => "repartidor", :name => "Repartidor")
empleo.sub_categories.find_or_create_by_key(:key => "vendedor", :name => "Vendedor")
empleo.sub_categories.find_or_create_by_key(:key => "voluntario", :name => "Voluntario")
empleo.sub_categories.find_or_create_by_key(:key => "otros_empleos", :name => "Otros empleos")

viajes_y_turismo = Category.find_or_create_by_key(:key => "viajes_y_turismo", :name => "Viajes y Turismo")
viajes_y_turismo.sub_categories.find_or_create_by_key(:key => "paquetes_y_promociones", :name => "Paquetes y Promociones")
viajes_y_turismo.sub_categories.find_or_create_by_key(:key => "alquileres_por_temporada", :name => "Alquileres por temporada")
viajes_y_turismo.sub_categories.find_or_create_by_key(:key => "paseos_guiados", :name => "Paseos Guiados")
viajes_y_turismo.sub_categories.find_or_create_by_key(:key => "hoteles_y_alojamiento", :name => "Hoteles y Alojamiento")

cursos_y_talleres = Category.find_or_create_by_key(:key => "cursos_y_talleres", :name => "Cursos y Talleres")
cursos_y_talleres.sub_categories.find_or_create_by_key(:key => "clases_particulares", :name => "Clases Particulares")
cursos_y_talleres.sub_categories.find_or_create_by_key(:key => "idiomas", :name => "Idiomas")
cursos_y_talleres.sub_categories.find_or_create_by_key(:key => "musica_teatro_y_arte", :name => "Música, Teatro y Arte")
cursos_y_talleres.sub_categories.find_or_create_by_key(:key => "informatica", :name => "Informática")
cursos_y_talleres.sub_categories.find_or_create_by_key(:key => "otros_cursos_y_talleres", :name => "Otros Cursos y Talleres")


servicios = Category.find_or_create_by_key(:key => "servicios", :name => "Servicios")
servicios.sub_categories.find_or_create_by_key(:key => "empleada_domestica", :name => "Empleada Doméstica")
servicios.sub_categories.find_or_create_by_key(:key => "internet", :name => "Internet")
servicios.sub_categories.find_or_create_by_key(:key => "informatica", :name => "Informática")
servicios.sub_categories.find_or_create_by_key(:key => "modelos_y_casting", :name => "Modelos y Casting")
servicios.sub_categories.find_or_create_by_key(:key => "eventos_y_fiestas", :name => "Eventos y Fiestas")
servicios.sub_categories.find_or_create_by_key(:key => "reparaciones", :name => "Reparaciones")
servicios.sub_categories.find_or_create_by_key(:key => "salud_y_belleza", :name => "Salud y Belleza")
servicios.sub_categories.find_or_create_by_key(:key => "transporte_y_mudanzas", :name => "Transporte y Mudanzas")

puts "Categories and Subcategories created"


Publication.create(:city_id => 62, :sub_category_id=>4, :title=>"Cuatri Banshee 350 Yamaha", :description=>"Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an...", :type=>"VehiculosPublication")
Publication.create(:city_id => 62, :sub_category_id=>4, :title=>"Raptor YFZ 700 ", :description=>"Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an...", :type=>"VehiculosPublication")