# -*- coding: utf-8 -*-
Option.create(:key => "facebook_app_id", :string_value => "615270258487238")
Option.create(:key => "facebook_secret_id", :string_value => "a0393230a7ff017fbc8d230b3fe9d567")

City.find_or_create_by_key(:key => "aguja_sur_cerro", :name => "Aguja Sur Cerro")
City.find_or_create_by_key(:key => "alto_rio_mayo", :name => "Alto Río Mayo")
City.find_or_create_by_key(:key => "alvarez_canadon", :name => "Alvarez Cañadón")
City.find_or_create_by_key(:key => "apeleg_arroyo", :name => "Apeleg Arroyo")
City.find_or_create_by_key(:key => "astra", :name => "Astra")
City.find_or_create_by_key(:key => "azul_cerro", :name => "Azul Cerro")
City.find_or_create_by_key(:key => "blancas_islas", :name => "Blancas Islas")
City.find_or_create_by_key(:key => "camarones_bahia", :name => "Camarones Bahía")
City.find_or_create_by_key(:key => "chico_rio", :name => "Chico Río")
City.find_or_create_by_key(:key => "chubut_rio", :name => "Chubut Río")
City.find_or_create_by_key(:key => "corcovado", :name => "Corcovado")
City.find_or_create_by_key(:key => "de_esquel_cordon", :name => "De Esquel Cordón")
City.find_or_create_by_key(:key => "dolavon", :name => "Dolavon")
City.find_or_create_by_key(:key => "el_maiten", :name => "El Maitén")
City.find_or_create_by_key(:key => "epuyen_lago", :name => "Epuyén Lago")
City.find_or_create_by_key(:key => "facundo", :name => "Facundo")
City.find_or_create_by_key(:key => "gaiman", :name => "Gaiman")
City.find_or_create_by_key(:key => "general_mosconi", :name => "General Mosconi")
City.find_or_create_by_key(:key => "gualjaina", :name => "Gualjaina")
City.find_or_create_by_key(:key => "lago_amutui_quimei", :name => "Lago Amutui Quimei")
City.find_or_create_by_key(:key => "parque_nacional_lago_puelo", :name => "Parque Nacional Lago Puelo")
City.find_or_create_by_key(:key => "peninsula_valdes", :name => "Península Valdés")
City.find_or_create_by_key(:key => "puerto_madryn", :name => "Puerto Madryn")
City.find_or_create_by_key(:key => "rada_tilly", :name => "Rada Tilly")
City.find_or_create_by_key(:key => "rio_mayo", :name => "Río Mayo")
City.find_or_create_by_key(:key => "sarmiento", :name => "Sarmiento")
City.find_or_create_by_key(:key => "sierra_chata", :name => "Sierra Chata")
City.find_or_create_by_key(:key => "steffen_cerro", :name => "Steffen Cerro")
City.find_or_create_by_key(:key => "taquetren_sierra", :name => "Taquetrén Sierra")
City.find_or_create_by_key(:key => "tova_isla", :name => "Tova Isla")
City.find_or_create_by_key(:key => "tres_picos_cerro", :name => "Tres Picos Cerro")
City.find_or_create_by_key(:key => "triste_monte", :name => "Triste Monte")
City.find_or_create_by_key(:key => "alto_de_las_plumas", :name => "Alto De Las Plumas")
City.find_or_create_by_key(:key => "alto_rio_senguer", :name => "Alto Río Senguer")
City.find_or_create_by_key(:key => "ameghino_punta", :name => "Ameghino Punta")
City.find_or_create_by_key(:key => "archibarca_cerro", :name => "Archibarca, Cerro")
City.find_or_create_by_key(:key => "atlas_punta", :name => "Atlas Punta")
City.find_or_create_by_key(:key => "bahia_bustamante", :name => "Bahía Bustamante")
City.find_or_create_by_key(:key => "camarones", :name => "Camarones")
City.find_or_create_by_key(:key => "aguja_sur_cerro", :name => "Aguja Sur Cerro")
City.find_or_create_by_key(:key => "canquel", :name => "Canquel")
City.find_or_create_by_key(:key => "cholila", :name => "Cholila")
City.find_or_create_by_key(:key => "comodoro_rivadavia", :name => "Comodoro Rivadavia")
City.find_or_create_by_key(:key => "cushamen", :name => "Cushamen")
City.find_or_create_by_key(:key => "de_la_virgen_cerro", :name => "De La Virgen Cerro")
City.find_or_create_by_key(:key => "el_hoyo", :name => "El Hoyo")
City.find_or_create_by_key(:key => "epuyen", :name => "Epuyén")
City.find_or_create_by_key(:key => "esquel", :name => "Esquel")
City.find_or_create_by_key(:key => "florentino_ameghino", :name => "Florentino Ameghino")
City.find_or_create_by_key(:key => "garayalde", :name => "Garayalde")
City.find_or_create_by_key(:key => "gobernador_costa", :name => "Gobernador Costa")
City.find_or_create_by_key(:key => "jose_de_san_martin", :name => "José De San Martín")
City.find_or_create_by_key(:key => "lago_puelo", :name => "Lago Puelo")
City.find_or_create_by_key(:key => "paso_de_indios", :name => "Paso De Indios")
City.find_or_create_by_key(:key => "playa_union", :name => "Playa Unión")
City.find_or_create_by_key(:key => "puerto_piramides", :name => "Puerto Pirámides")
City.find_or_create_by_key(:key => "rawson", :name => "Rawson")
City.find_or_create_by_key(:key => "rio_pico", :name => "Río Pico")
City.find_or_create_by_key(:key => "seca_laguna", :name => "Seca Laguna")
City.find_or_create_by_key(:key => "solano_bahia", :name => "Solano Bahía")
City.find_or_create_by_key(:key => "talagapa", :name => "Talagapa")
City.find_or_create_by_key(:key => "telsen", :name => "Telsen")
City.find_or_create_by_key(:key => "trelew", :name => "Trelew")
City.find_or_create_by_key(:key => "trevelin", :name => "Trevelin")
City.find_or_create_by_key(:key => "verde_laguna", :name => "Verde Laguna")
puts "Cities created"

compra_venta = Category.find_or_create_by_key(:key => "compra_venta", :name => "Compra - Venta")
compra_venta.sub_categories.find_or_create_by_key(:key => "animales_y_mascotas", :name => "Animales y Mascotas")
compra_venta.sub_categories.find_or_create_by_key(:key => "cd_dvd", :name => "CD - DVD")
compra_venta.sub_categories.find_or_create_by_key(:key => "comida", :name => "Comida y Alimentos")
compra_venta.sub_categories.find_or_create_by_key(:key => "celulares_y_telefonos", :name => "Celulares y Teléfonos")
compra_venta.sub_categories.find_or_create_by_key(:key => "coleccionables", :name => "Coleccionables")
compra_venta.sub_categories.find_or_create_by_key(:key => "computacion_y_electronica", :name => "Computación y Electrónica")
compra_venta.sub_categories.find_or_create_by_key(:key => "instrumentos_musicales", :name => "Instrumentos Musicales")
compra_venta.sub_categories.find_or_create_by_key(:key => "electrodomesticos", :name => "Electrodomésticos")
compra_venta.sub_categories.find_or_create_by_key(:key => "deportes", :name => "Deportes")
compra_venta.sub_categories.find_or_create_by_key(:key => "fotografia_y_video", :name => "Fotografía y Video")
compra_venta.sub_categories.find_or_create_by_key(:key => "libros_y_revistas", :name => "Libros y Revistras")
compra_venta.sub_categories.find_or_create_by_key(:key => "hogar", :name => "Hogar")
compra_venta.sub_categories.find_or_create_by_key(:key => "bebes y niños", :name => "Bebés y Niños")
compra_venta.sub_categories.find_or_create_by_key(:key => "joyas_y_relojes", :name => "Joyas y Relojes")
compra_venta.sub_categories.find_or_create_by_key(:key => "indumentaria", :name => "Indumentaria")
compra_venta.sub_categories.find_or_create_by_key(:key => "juguetes_y_juegos", :name => "Juguetes y Juegos")
compra_venta.sub_categories.find_or_create_by_key(:key => "salud_y_belleza", :name => "Salud y Belleza")
compra_venta.sub_categories.find_or_create_by_key(:key => "videojuegos", :name => "Videojuegos")
compra_venta.sub_categories.find_or_create_by_key(:key => "otras_categorias", :name => "Otras Categorías")

inmuebles = Category.find_or_create_by_key(:key => "inmuebles", :name => "Inmuebles")
inmuebles.sub_categories.find_or_create_by_key(:key => "terrenos_y_lotes", :name => "Terrenos y Lotes")
inmuebles.sub_categories.find_or_create_by_key(:key => "locales_y_oficinas", :name => "Locales y Oficinas")
inmuebles.sub_categories.find_or_create_by_key(:key => "estacionamiento", :name => "Estacionamiento")
inmuebles.sub_categories.find_or_create_by_key(:key => "en_venta", :name => "En Venta")
inmuebles.sub_categories.find_or_create_by_key(:key => "en_alquiler", :name => "En Alquiler")


vehiculos_y_accesorios = Category.find_or_create_by_key(:key => "vehiculos_y_accesorios", :name => "Vehículos y Accesorios")
vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "autos_y_camionetas", :name => "Autos y Camionetas")
vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "camiones_y_colectivos", :name => "Camiones y Colectivos")
vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "casillas_y_casas_rodantes", :name => "Casillas y Casas Rodantes")
vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "motos_y_cuatriciclos", :name => "Motos y Cuatriciclos")

nautica_sub_category = vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "nautica", :name => "Náutica")
nautica_sub_category.sub_sub_categories.find_or_create_by_key(:key => "botes", :name => "Botes")
nautica_sub_category.sub_sub_categories.find_or_create_by_key(:key => "canoas", :name => "Canoas")
nautica_sub_category.sub_sub_categories.find_or_create_by_key(:key => "cruceros", :name => "Cruceros")
nautica_sub_category.sub_sub_categories.find_or_create_by_key(:key => "embarcaciones_a_vela", :name => "Embarcaciones a vela")
nautica_sub_category.sub_sub_categories.find_or_create_by_key(:key => "gomones", :name => "Gomones")
nautica_sub_category.sub_sub_categories.find_or_create_by_key(:key => "kayak", :name => "Kayak")
nautica_sub_category.sub_sub_categories.find_or_create_by_key(:key => "lanchas", :name => "Lanchas")
nautica_sub_category.sub_sub_categories.find_or_create_by_key(:key => "motos_de_agua", :name => "Motos de agua")
nautica_sub_category.sub_sub_categories.find_or_create_by_key(:key => "semirigidos", :name => "Semirígidos")
nautica_sub_category.sub_sub_categories.find_or_create_by_key(:key => "otra_categoria", :name => "Otra categoría")

vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "aviones_y_avionetas", :name => "Aviones y Avionetas")
vehiculos_y_accesorios.sub_categories.find_or_create_by_key(:key => "otras_categorias", :name => "Otras Categorías")



empleo = Category.find_or_create_by_key(:key => "empleo", :name => "Empleo")
empleo.sub_categories.find_or_create_by_key(:key => "abogado", :name => "Abogado")
empleo.sub_categories.find_or_create_by_key(:key => "administrativo", :name => "Administrativo")
empleo.sub_categories.find_or_create_by_key(:key => "animador_y_actor", :name => "Animador y Actor")
empleo.sub_categories.find_or_create_by_key(:key => "comercial", :name => "Comercial")
empleo.sub_categories.find_or_create_by_key(:key => "construccion_y_obras", :name => "Construcción y Obras")
empleo.sub_categories.find_or_create_by_key(:key => "contador_y_financiero", :name => "Contador y Financiero")
empleo.sub_categories.find_or_create_by_key(:key => "educacion", :name => "Educación")
empleo.sub_categories.find_or_create_by_key(:key => "hoteleria_y_turismo", :name => "Hotelería y Turismo")
empleo.sub_categories.find_or_create_by_key(:key => "informatica_y_multimedia", :name => "Informática y Multimedia")
empleo.sub_categories.find_or_create_by_key(:key => "ingeniero", :name => "Ingeniero")
empleo.sub_categories.find_or_create_by_key(:key => "inmobiliaria", :name => "Inmobiliaria")
empleo.sub_categories.find_or_create_by_key(:key => "publicidad_y_marketing", :name => "Publicidad y Marketing")
empleo.sub_categories.find_or_create_by_key(:key => "medicina_y_salud", :name => "Medicina y Salud")
empleo.sub_categories.find_or_create_by_key(:key => "operario", :name => "Operario")
empleo.sub_categories.find_or_create_by_key(:key => "relaciones_publicas", :name => "Relaciones Públicas")
empleo.sub_categories.find_or_create_by_key(:key => "recursos_humanos", :name => "Recursos Humanos")
empleo.sub_categories.find_or_create_by_key(:key => "mozos_y_restaurantes", :name => "Mozos y Restaurantes")
empleo.sub_categories.find_or_create_by_key(:key => "repartidor", :name => "Repartidor")
empleo.sub_categories.find_or_create_by_key(:key => "vendedor", :name => "Vendedor")
empleo.sub_categories.find_or_create_by_key(:key => "voluntario", :name => "Voluntario")
empleo.sub_categories.find_or_create_by_key(:key => "otros_empleos", :name => "Otros empleos")

viajes_y_turismo = Category.find_or_create_by_key(:key => "viajes_y_turismo", :name => "Viajes y Turismo")
viajes_y_turismo.sub_categories.find_or_create_by_key(:key => "paquetes_y_promociones", :name => "Paquetes y Promociones")
viajes_y_turismo.sub_categories.find_or_create_by_key(:key => "alquileres_por_temporada", :name => "Alquileres por temporada")
viajes_y_turismo.sub_categories.find_or_create_by_key(:key => "paseos_guiados", :name => "Paseos Guiados")
viajes_y_turismo.sub_categories.find_or_create_by_key(:key => "hoteles_y_alojamiento", :name => "Hoteles y Alojamiento")

cursos_y_talleres = Category.find_or_create_by_key(:key => "cursos_y_talleres", :name => "Cursos y Talleres")
cursos_y_talleres.sub_categories.find_or_create_by_key(:key => "clases_particulares", :name => "Clases Particulares")
cursos_y_talleres.sub_categories.find_or_create_by_key(:key => "idiomas", :name => "Idiomas")
cursos_y_talleres.sub_categories.find_or_create_by_key(:key => "musica_teatro_y_arte", :name => "Música, Teatro y Arte")
cursos_y_talleres.sub_categories.find_or_create_by_key(:key => "informatica", :name => "Informática")
cursos_y_talleres.sub_categories.find_or_create_by_key(:key => "otros_cursos_y_talleres", :name => "Otros Cursos y Talleres")


servicios = Category.find_or_create_by_key(:key => "servicios", :name => "Servicios")
servicios.sub_categories.find_or_create_by_key(:key => "empleada_domestica", :name => "Empleada Doméstica")
servicios.sub_categories.find_or_create_by_key(:key => "internet", :name => "Internet")
servicios.sub_categories.find_or_create_by_key(:key => "informatica", :name => "Informática")
servicios.sub_categories.find_or_create_by_key(:key => "modelos_y_casting", :name => "Modelos y Casting")
servicios.sub_categories.find_or_create_by_key(:key => "eventos_y_fiestas", :name => "Eventos y Fiestas")
servicios.sub_categories.find_or_create_by_key(:key => "reparaciones", :name => "Reparaciones")
servicios.sub_categories.find_or_create_by_key(:key => "salud_y_belleza", :name => "Salud y Belleza")
servicios.sub_categories.find_or_create_by_key(:key => "transporte_y_mudanzas", :name => "Transporte y Mudanzas")

puts "Categories, Subcategories and SubSubcategories created"




CarBrand.find_or_create_by_key(:key=>"acura", :name=>"Acura")
CarBrand.find_or_create_by_key(:key=>"alfa_romeo", :name=>"Alfa Romeo")
CarBrand.find_or_create_by_key(:key=>"audi", :name=>"Audi")
CarBrand.find_or_create_by_key(:key=>"bmw", :name=>"BMW")
CarBrand.find_or_create_by_key(:key=>"buggy", :name=>"Buggy")
CarBrand.find_or_create_by_key(:key=>"cadillac", :name=>"Cadillac")
CarBrand.find_or_create_by_key(:key=>"chevrolet", :name=>"Chevrolet")
CarBrand.find_or_create_by_key(:key=>"citroen", :name=>"Citroen")
CarBrand.find_or_create_by_key(:key=>"fiat", :name=>"Fiat")
CarBrand.find_or_create_by_key(:key=>"ford", :name=>"Ford")
CarBrand.find_or_create_by_key(:key=>"honda", :name=>"Honda")
CarBrand.find_or_create_by_key(:key=>"peugeot", :name=>"Peugeot")
CarBrand.find_or_create_by_key(:key=>"renault", :name=>"Renault")
CarBrand.find_or_create_by_key(:key=>"suzuki", :name=>"Suzuki")
CarBrand.find_or_create_by_key(:key=>"toyota", :name=>"Toyota")
CarBrand.find_or_create_by_key(:key=>"volkswagen", :name=>"Volkswagen")
CarBrand.find_or_create_by_key(:key=>"chery", :name=>"Chery")
CarBrand.find_or_create_by_key(:key=>"chrysler", :name=>"Chrysler")
CarBrand.find_or_create_by_key(:key=>"dacia", :name=>"Dacia")
CarBrand.find_or_create_by_key(:key=>"daewoo", :name=>"Daewoo")
CarBrand.find_or_create_by_key(:key=>"daihatsu", :name=>"Daihatsu")
CarBrand.find_or_create_by_key(:key=>"dodge", :name=>"Dodge")
CarBrand.find_or_create_by_key(:key=>"galloper", :name=>"Galloper")
CarBrand.find_or_create_by_key(:key=>"gmc", :name=>"GMC")
CarBrand.find_or_create_by_key(:key=>"hiundai", :name=>"Hiundai")
CarBrand.find_or_create_by_key(:key=>"ika", :name=>"Ika")
CarBrand.find_or_create_by_key(:key=>"isuzu", :name=>"Isuzu")
CarBrand.find_or_create_by_key(:key=>"iveco", :name=>"Iveco")
CarBrand.find_or_create_by_key(:key=>"jeep", :name=>"Jeep")
CarBrand.find_or_create_by_key(:key=>"kia", :name=>"Kia")
CarBrand.find_or_create_by_key(:key=>"lada", :name=>"Lada")
CarBrand.find_or_create_by_key(:key=>"land_rover", :name=>"Land Rover")
CarBrand.find_or_create_by_key(:key=>"mazda", :name=>"Mazda")
CarBrand.find_or_create_by_key(:key=>"mercedes_benz", :name=>"Mercedes Benz")
CarBrand.find_or_create_by_key(:key=>"mini", :name=>"Mini")
CarBrand.find_or_create_by_key(:key=>"mitsubishi", :name=>"Mitsubishi")
CarBrand.find_or_create_by_key(:key=>"nissan", :name=>"Nissan")
CarBrand.find_or_create_by_key(:key=>"rastrojero", :name=>"Rastrojero")
CarBrand.find_or_create_by_key(:key=>"rover", :name=>"Rover")
CarBrand.find_or_create_by_key(:key=>"seat", :name=>"Seat")
CarBrand.find_or_create_by_key(:key=>"smart", :name=>"Smart")
CarBrand.find_or_create_by_key(:key=>"subaru", :name=>"Subaru")
CarBrand.find_or_create_by_key(:key=>"tata", :name=>"Tata")
CarBrand.find_or_create_by_key(:key=>"volvo", :name=>"Volvo")
CarBrand.find_or_create_by_key(:key=>"willys", :name=>"Willys")
CarBrand.find_or_create_by_key(:key=>"otras_marcas", :name=>"Otras Marcas")

TruckBrand.find_or_create_by_key(:key=>"3_star", :name=>"3-Star")
TruckBrand.find_or_create_by_key(:key=>"agrale", :name=>"Agrale")
TruckBrand.find_or_create_by_key(:key=>"blac", :name=>"Blac")
TruckBrand.find_or_create_by_key(:key=>"chevrolet", :name=>"Chevrolet")
TruckBrand.find_or_create_by_key(:key=>"daihatsu", :name=>"Daihatsu")
TruckBrand.find_or_create_by_key(:key=>"dfm", :name=>"DFM")
TruckBrand.find_or_create_by_key(:key=>"deutz_agrale", :name=>"Deutz Agrale")
TruckBrand.find_or_create_by_key(:key=>"dodge", :name=>"Dodge")
TruckBrand.find_or_create_by_key(:key=>"efm", :name=>"EFM")
TruckBrand.find_or_create_by_key(:key=>"feresa", :name=>"F.E.R.E.S.A.")
TruckBrand.find_or_create_by_key(:key=>"fiat", :name=>"Fiat")
TruckBrand.find_or_create_by_key(:key=>"ford", :name=>"Ford")
TruckBrand.find_or_create_by_key(:key=>"gaz", :name=>"GAZ")
TruckBrand.find_or_create_by_key(:key=>"heibao", :name=>"Heibao")
TruckBrand.find_or_create_by_key(:key=>"hiundai", :name=>"Hiundai")
TruckBrand.find_or_create_by_key(:key=>"international", :name=>"International")
TruckBrand.find_or_create_by_key(:key=>"isuzu", :name=>"Isuzu")
TruckBrand.find_or_create_by_key(:key=>"kia", :name=>"Kia")
TruckBrand.find_or_create_by_key(:key=>"mercedes_benz", :name=>"Mercedes Benz")
TruckBrand.find_or_create_by_key(:key=>"mitsubishi", :name=>"Mitsubishi")
TruckBrand.find_or_create_by_key(:key=>"nissan", :name=>"Nissan")
TruckBrand.find_or_create_by_key(:key=>"prosal", :name=>"Prosal")
TruckBrand.find_or_create_by_key(:key=>"renault", :name=>"Renault")
TruckBrand.find_or_create_by_key(:key=>"sanxings", :name=>"Sanxings")
TruckBrand.find_or_create_by_key(:key=>"scania", :name=>"Scania")
TruckBrand.find_or_create_by_key(:key=>"tata", :name=>"Tata")
TruckBrand.find_or_create_by_key(:key=>"toyota", :name=>"Toyota")
TruckBrand.find_or_create_by_key(:key=>"volare", :name=>"Volare")
TruckBrand.find_or_create_by_key(:key=>"volvo", :name=>"Volvo")
TruckBrand.find_or_create_by_key(:key=>"volkswagen", :name=>"Volkswagen")
TruckBrand.find_or_create_by_key(:key=>"otras_marcas", :name=>"Otras Marcas")

MotoBrand.find_or_create_by_key(:key=>"appia", :name=>"Appia")
MotoBrand.find_or_create_by_key(:key=>"aprilia", :name=>"Aprilia")
MotoBrand.find_or_create_by_key(:key=>"bmw", :name=>"BMW")
MotoBrand.find_or_create_by_key(:key=>"baboon", :name=>"Baboon")
MotoBrand.find_or_create_by_key(:key=>"bajaj", :name=>"Bajaj")
MotoBrand.find_or_create_by_key(:key=>"beta", :name=>"Beta")
MotoBrand.find_or_create_by_key(:key=>"big_warrior", :name=>"Big Warrior")
MotoBrand.find_or_create_by_key(:key=>"bloower", :name=>"Bloower")
MotoBrand.find_or_create_by_key(:key=>"boes", :name=>"Boes")
MotoBrand.find_or_create_by_key(:key=>"bombardier", :name=>"Bombardier")
MotoBrand.find_or_create_by_key(:key=>"brava", :name=>"Brava")
MotoBrand.find_or_create_by_key(:key=>"cagiva", :name=>"Cagiva")
MotoBrand.find_or_create_by_key(:key=>"can_am", :name=>"Can Am")
MotoBrand.find_or_create_by_key(:key=>"cerro", :name=>"Cerro")
MotoBrand.find_or_create_by_key(:key=>"chery", :name=>"Chery")
MotoBrand.find_or_create_by_key(:key=>"corven", :name=>"Corven")
MotoBrand.find_or_create_by_key(:key=>"crossquads", :name=>"Crossquads")
MotoBrand.find_or_create_by_key(:key=>"dkw", :name=>"DKW")
MotoBrand.find_or_create_by_key(:key=>"da_dalt", :name=>"Da dalt")
MotoBrand.find_or_create_by_key(:key=>"daelim", :name=>"Daelim")
MotoBrand.find_or_create_by_key(:key=>"dayama", :name=>"Dayama")
MotoBrand.find_or_create_by_key(:key=>"dayang", :name=>"Dayang")
MotoBrand.find_or_create_by_key(:key=>"daytona", :name=>"Daytona")
MotoBrand.find_or_create_by_key(:key=>"derbi", :name=>"Derbi")
MotoBrand.find_or_create_by_key(:key=>"di_blasi", :name=>"Di Blasi")
MotoBrand.find_or_create_by_key(:key=>"ducati", :name=>"Ducati")
MotoBrand.find_or_create_by_key(:key=>"famsa", :name=>"Famsa")
MotoBrand.find_or_create_by_key(:key=>"farspeed", :name=>"Farspeed")
MotoBrand.find_or_create_by_key(:key=>"bgk", :name=>"GBK")
MotoBrand.find_or_create_by_key(:key=>"gamma", :name=>"Gamma")
MotoBrand.find_or_create_by_key(:key=>"garelli", :name=>"Garelli")
MotoBrand.find_or_create_by_key(:key=>"gas_gas", :name=>"Gas Gas")
MotoBrand.find_or_create_by_key(:key=>"genesis", :name=>"Genesis")
MotoBrand.find_or_create_by_key(:key=>"gilera", :name=>"Gilera")
MotoBrand.find_or_create_by_key(:key=>"goes", :name=>"Goes")
MotoBrand.find_or_create_by_key(:key=>"gerrero", :name=>"Gerrero")
MotoBrand.find_or_create_by_key(:key=>"guzzi", :name=>"Guzzi")
MotoBrand.find_or_create_by_key(:key=>"harley_davidson", :name=>"Harley Davidson")
MotoBrand.find_or_create_by_key(:key=>"hava", :name=>"Hava")
MotoBrand.find_or_create_by_key(:key=>"honda", :name=>"Honda")
MotoBrand.find_or_create_by_key(:key=>"hunter", :name=>"Hunter")
MotoBrand.find_or_create_by_key(:key=>"hunter_atv", :name=>"Hunter ATV")
MotoBrand.find_or_create_by_key(:key=>"husanberg", :name=>"Husanberg")
MotoBrand.find_or_create_by_key(:key=>"husqvarna", :name=>"Husqvarna")
MotoBrand.find_or_create_by_key(:key=>"imsa", :name=>"IMSA")
MotoBrand.find_or_create_by_key(:key=>"jaam", :name=>"Jaam")
MotoBrand.find_or_create_by_key(:key=>"jaguar", :name=>"Jaguar")
MotoBrand.find_or_create_by_key(:key=>"jawa", :name=>"Jawa")
MotoBrand.find_or_create_by_key(:key=>"jianshe", :name=>"Jianshe")
MotoBrand.find_or_create_by_key(:key=>"jincheng", :name=>"Jincheng")
MotoBrand.find_or_create_by_key(:key=>"jinma", :name=>"Jinma")
MotoBrand.find_or_create_by_key(:key=>"jonway", :name=>"Jonway")
MotoBrand.find_or_create_by_key(:key=>"jordan", :name=>"Jordan")
MotoBrand.find_or_create_by_key(:key=>"juki", :name=>"Juki")
MotoBrand.find_or_create_by_key(:key=>"kml", :name=>"KML")
MotoBrand.find_or_create_by_key(:key=>"ktm", :name=>"KTM")
MotoBrand.find_or_create_by_key(:key=>"kawasaki", :name=>"Kawasaki")
MotoBrand.find_or_create_by_key(:key=>"keeway", :name=>"Keeway")
MotoBrand.find_or_create_by_key(:key=>"keller", :name=>"Keller")
MotoBrand.find_or_create_by_key(:key=>"kikai", :name=>"Kikai")
MotoBrand.find_or_create_by_key(:key=>"kin_road", :name=>"Kin Road")
MotoBrand.find_or_create_by_key(:key=>"kimco", :name=>"Kimco")
MotoBrand.find_or_create_by_key(:key=>"longstar", :name=>"Longstar")
MotoBrand.find_or_create_by_key(:key=>"luckylion", :name=>"Luckylion")
MotoBrand.find_or_create_by_key(:key=>"mpr", :name=>"MPR")
MotoBrand.find_or_create_by_key(:key=>"maverick", :name=>"Maverick")
MotoBrand.find_or_create_by_key(:key=>"mini", :name=>"Mini")
MotoBrand.find_or_create_by_key(:key=>"mondial", :name=>"Mondial")
MotoBrand.find_or_create_by_key(:key=>"montelli_motorcycles", :name=>"Montelli Motorcycles")
MotoBrand.find_or_create_by_key(:key=>"motomel", :name=>"Motomel")
MotoBrand.find_or_create_by_key(:key=>"nsu", :name=>"NSU")
MotoBrand.find_or_create_by_key(:key=>"norton", :name=>"Norton")
MotoBrand.find_or_create_by_key(:key=>"olmo", :name=>"Olmo")
MotoBrand.find_or_create_by_key(:key=>"outlander", :name=>"Outlander")
MotoBrand.find_or_create_by_key(:key=>"panther", :name=>"Panther")
MotoBrand.find_or_create_by_key(:key=>"peak", :name=>"Peak")
MotoBrand.find_or_create_by_key(:key=>"peugeot", :name=>"Peugeot")
MotoBrand.find_or_create_by_key(:key=>"piaggio", :name=>"Piaggio")
MotoBrand.find_or_create_by_key(:key=>"piaggio_vespa", :name=>"Piaggio Vespa")
MotoBrand.find_or_create_by_key(:key=>"pitbull", :name=>"Pitbull")
MotoBrand.find_or_create_by_key(:key=>"polaris", :name=>"Polaris")
MotoBrand.find_or_create_by_key(:key=>"puma", :name=>"Puma")
MotoBrand.find_or_create_by_key(:key=>"rafter", :name=>"Rafter")
MotoBrand.find_or_create_by_key(:key=>"royal_enfield", :name=>"Royal Enfield")
MotoBrand.find_or_create_by_key(:key=>"rumi", :name=>"Rumi")
MotoBrand.find_or_create_by_key(:key=>"sym", :name=>"SYM")
MotoBrand.find_or_create_by_key(:key=>"scout", :name=>"Scout")
MotoBrand.find_or_create_by_key(:key=>"sea_horse", :name=>"Sea Horse")
MotoBrand.find_or_create_by_key(:key=>"siambretta", :name=>"Siambretta")
MotoBrand.find_or_create_by_key(:key=>"sumo", :name=>"Sumo")
MotoBrand.find_or_create_by_key(:key=>"suzuki", :name=>"Suzuki")
MotoBrand.find_or_create_by_key(:key=>"tibo", :name=>"Tibo")
MotoBrand.find_or_create_by_key(:key=>"tiger", :name=>"Tiger")
MotoBrand.find_or_create_by_key(:key=>"triton", :name=>"Triton")
MotoBrand.find_or_create_by_key(:key=>"triumph", :name=>"Triumph")
MotoBrand.find_or_create_by_key(:key=>"united_motors", :name=>"United Motors")
MotoBrand.find_or_create_by_key(:key=>"vaado", :name=>"Vaado")
MotoBrand.find_or_create_by_key(:key=>"velimotor", :name=>"Velimotor")
MotoBrand.find_or_create_by_key(:key=>"vento", :name=>"Vento")
MotoBrand.find_or_create_by_key(:key=>"vespa", :name=>"Vespa")
MotoBrand.find_or_create_by_key(:key=>"x_quad", :name=>"X Quad")
MotoBrand.find_or_create_by_key(:key=>"x_screams", :name=>"X-Screams")
MotoBrand.find_or_create_by_key(:key=>"xingyue", :name=>"Xingyue")
MotoBrand.find_or_create_by_key(:key=>"yamaha", :name=>"Yamaha")
MotoBrand.find_or_create_by_key(:key=>"zanella", :name=>"Zanella")
MotoBrand.find_or_create_by_key(:key=>"otra_marca", :name=>"Otra marca")



puts "Brands created"

#Publication.create(:city_id => 62, :sub_category_id=>4, :title=>"Cuatri Banshee 350 Yamaha", :description=>"Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an...", :type=>"VehiculosPublication")
#Publication.create(:city_id => 62, :sub_category_id=>4, :title=>"Raptor YFZ 700 ", :description=>"Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an... Lorem Ipsum is simply dummy text of the printing an...", :type=>"VehiculosPublication")